ALTER TABLE pets ADD COLUMN id INT required primary_key;
ALTER TABLE pets ADD COLUMN id INT required primary_key;
ALTER TABLE pets ADD COLUMN gender VARCHAR(25) NOT NULL none;
ALTER TABLE pets ADD COLUMN gender VARCHAR(25) none;
ALTER TABLE pets DROP COLUMN gender;
ALTER TABLE pets ADD COLUMN id INT required primary_key;
ALTER TABLE pets ADD COLUMN gender VARCHAR(25) NOT NULL none;
ALTER TABLE pets ADD COLUMN gender VARCHAR(25) none;
ALTER TABLE pets DROP COLUMN gender;
ALTER TABLE pets ADD COLUMN animal_type VARCHAR(120) NOT NULL required;
ALTER TABLE pets ADD COLUMN animal_type VARCHAR(120) required;
ALTER TABLE pets DROP COLUMN animal_type;
ALTER TABLE pets ADD COLUMN id INT required primary_key;
ALTER TABLE pets ADD COLUMN gender VARCHAR(25) NOT NULL none;
ALTER TABLE pets ADD COLUMN gender VARCHAR(25) none;
ALTER TABLE pets DROP COLUMN gender;
ALTER TABLE pets ADD COLUMN animal_type VARCHAR(120) NOT NULL required;
ALTER TABLE pets ADD COLUMN animal_type VARCHAR(120) required;
ALTER TABLE pets DROP COLUMN animal_type;
ALTER TABLE pets ADD COLUMN age INT none;
