ALTER TABLE pets ADD COLUMN gender VARCHAR(25) NOT NULL none;
ALTER TABLE pets ADD COLUMN gender VARCHAR(25) NOT NULL none;
ALTER TABLE pets ADD COLUMN animal_type VARCHAR(120) NOT NULL required;
ALTER TABLE pets ADD COLUMN gender VARCHAR(25) NOT NULL none;
ALTER TABLE pets ADD COLUMN animal_type VARCHAR(120) NOT NULL required;
