//! The OpenAPI document and the Hey API config file.

use super::{paths, schemas, Operation};
use crate::database::introspection::Schema;
use crate::generators::typescript::casing::Casing;

/// Renders the OpenAPI 3.1 document.
pub(super) fn document(schema: &Schema, casing: Casing, operations: &[Operation]) -> String {
    format!(
        "{{\n\
         \x20 \"openapi\": \"3.1.0\",\n\
         \x20 \"info\": {{\n\
         \x20   \"title\": \"Generated API\",\n\
         \x20   \"version\": \"1.0.0\",\n\
         \x20   \"description\": \"Generated by rustyroad pull from the database schema.\"\n\
         \x20 }},\n\
         \x20 \"paths\": {{\n{}\n  }},\n\
         \x20 \"components\": {{\n\
         \x20   \"schemas\": {{\n{}\n    }}\n\
         \x20 }}\n\
         }}\n",
        paths::render(operations),
        schemas::render(schema, casing)
    )
}

/// Renders `openapi-ts.config.ts`.
///
/// `asClass: false` yields flat functions, so a call site reads
/// `listUsers({ ... })` rather than going through a class instance.
pub(super) fn config() -> String {
    String::from(
        "import { defineConfig } from \"@hey-api/openapi-ts\";\n\n\
         // Generated by rustyroad pull. Adjust `output` to suit your project.\n\
         //\n\
         // Note: @hey-api/openapi-ts 0.87.x requires TypeScript 5; under\n\
         // TypeScript 7 it fails reading 'LineFeed'.\n\
         export default defineConfig({\n\
         \tinput: process.env.OPENAPI_INPUT || \"./openapi.json\",\n\
         \toutput: \"./generated\",\n\
         \tplugins: [\n\
         \t\t{ enums: \"javascript\", name: \"@hey-api/typescript\" },\n\
         \t\t{ name: \"@hey-api/sdk\", asClass: false },\n\
         \t],\n\
         });\n",
    )
}
