
CREATE TABLE IF NOT EXISTS page (
    id SERIAL PRIMARY KEY,
    title TEXT,
    html_content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    associated_user_id INTEGER NOT NULL,
    summary TEXT,
    author TEXT,
    excerpt TEXT,
    slug TEXT,
    page_status TEXT,
    author_image TEXT,
    author_thumbnail TEXT,
    author_url TEXT,
    featured_image TEXT,
    featured_image_thumbnail TEXT,
    seo_title TEXT,
    seo_description TEXT,
    seo_keywords TEXT,
    seo_focus_keyphrase TEXT,
    seo_canonical_url TEXT,
    seo_no_index BOOLEAN,
    seo_no_follow BOOLEAN,
    seo_og_title TEXT,
    seo_og_locale TEXT,
    seo_og_type TEXT,
    seo_og_description TEXT,
    seo_og_image TEXT,
    seo_og_image_width INTEGER,
    seo_og_image_height INTEGER,
    seo_twitter_title TEXT,
    seo_twitter_description TEXT,
    seo_twitter_image TEXT,
    seo_twitter_image_alt TEXT,
    seo_twitter_card TEXT,
    schema_type TEXT,
    schema_page_type TEXT,
    schema_article_type TEXT,
    schema_description TEXT,
    schema_author TEXT,
    schema_publisher TEXT,
    schema_image TEXT,
    schema_url TEXT,
    schema_name TEXT,
    schema_headline TEXT,
    schema_date_published TIMESTAMP,
    schema_date_modified TIMESTAMP
);
    