use chrono::DateTime;
// this actually needs to be generated by the cli
pub struct HtmlGrapesJs {
    // fields go here
    pub id: i32,
    pub html_content: String,
    pub created_at: DateTime<chrono::Utc>,
    pub updated_at: DateTime<chrono::Utc>,
    pub associated_user_id: i32,
    pub metadata: String,
}